check for app

diff --git a/jup b/jup
--- a/jup
+++ b/jup
@@ -15,6 +15,10 @@
 #    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
 #        -keyout ~/.jupyter/mykey.key -out ~/.jupyter/mycert.pem
 #
+#  Requirements:
+#    GNU grep as ggrep (install via MacPorts)
+#    GNU awk as gawk (install via MacPorts)
+#
 #  Exit status:
 #     0: No error
 #     1: Cannot access ~/.jupyter
@@ -27,11 +31,12 @@
 #     8: Cannot write to ~/.jupyter/run.log
 #     9: Cannot write to ~/.jupyter/pid.log
 #    10: Unknown operating system
-#    11: No IPv4 address found
-#    12: Invalid IPv4 address
+#    11: App not found
+#    12: No IPv4 address found
+#    13: Invalid IPv4 address
 #
-#  Version : 1.0
-#  Date    : 2020-08-09
+#  Version : 1.1
+#  Date    : 2021-04-28
 #  Author  : E. Dronkert https://github.com/ednl
 #  License : MIT (free to use with attribution to the author)
 #
@@ -78,24 +83,30 @@ if [ "$1" = "start" ]; then
 
 	if [ "$SYST" = "Linux" ]; then
 		APP=jupyter-notebook
-		IP=$(ip -4 -br a | grep UP | head -n 1 | awk '{print $3}' | cut -d'/' -f1)
+		IP=$(ip -4 -br a | ggrep UP | head -n 1 | gawk '{print $3}' | cut -d'/' -f1)
 	elif [ "$SYST" = "Darwin" ]; then
-		APP=jupyter-notebook-3.8
-		INTF=$(ifconfig | grep '^en.*<UP' | head -n 1 | cut -d':' -f1)
-		IP=$(ifconfig "$INTF" inet | tail -n 1 | awk '{print $2}')
+		APP=jupyter-notebook-3.9
+		INTF=$(ifconfig | ggrep '^en.*<UP' | head -n 1 | cut -d':' -f1)
+		IP=$(ifconfig "$INTF" inet | tail -n 1 | gawk '{print $2}')
 	else
 		echo "Unknown operating system: $SYST" >&2
 		exit 10
 	fi
 
-	[ -z "$IP" ] && { echo "No IPv4 address found" >&2; exit 11; }
-	echo "$IP" | grep -q -s -P '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$' || { echo "Invalid IPv4 address: $IP" >&2; exit 12; }
+	# Check if app exists
+	[ -n "$(which ${APP})" ] || { echo "App not found: $APP" >&2; exit 11; }
+
+	[ -z "$IP" ] && { echo "No IPv4 address found" >&2; exit 12; }
+	echo "$IP" | ggrep -q -s -P '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$' || { echo "Invalid IPv4 address: $IP" >&2; exit 13; }
 
 	echo -n "Starting Jupyter Notebook server ... "
+	#$APP > "$LOG" 2>&1 &
 	$APP --ip "$IP" --port "$PORT" --no-browser --certfile "$CER" --keyfile "$KEY" > "$LOG" 2>&1 &
 	echo $! > "$PID"
 	echo "OK"
-	echo "https://${HOST,,}:$PORT"  # lowercase host name
+
+	# Lowercase host name
+	echo "https://${HOST,,}:$PORT"
 	echo "https://$IP:$PORT"
 	exit 0
 fi
